/**
 * The `user_supplied_garment` source.
 *
 * WHAT IT MEANS. "The authenticated client is supplying bounded garment media
 * for this explicit Virtual Try-On request." Nothing more. Today the one
 * producer is a photo the customer gave Elise, which lives only on their
 * device, so the server can neither look it up by id nor fetch it from a URL.
 *
 * WHAT IT DOES NOT MEAN. Not owned, not purchased, not saved to the Closet,
 * not a verified retailer product, not "generated by Elise", and not a trusted
 * URL. It grants no privilege a plain authenticated K+ try-on request does not
 * already have: identity, the account guard, the kill switch, K+, the quota
 * reservation and the provider choice are all decided before and around this
 * module, exactly as they are for every other source.
 *
 * WHAT THE CONTENT HASH IS FOR. The client sends the fingerprint the offer was
 * created for; this module RECOMPUTES the hash from the bytes and requires
 * equality. That proves the request is internally consistent -- these bytes are
 * the bytes that fingerprint names -- and that is all it proves. It is not
 * authorization, not ownership, and not evidence of where the image came from.
 *
 * WHAT THIS MODULE CHECKS, in order, cheapest first:
 *
 *   - the source reference has exactly the expected shape;
 *   - the payload is inside its own explicit encoded bound;
 *   - it is an approved media type, shaped as a data URI;
 *   - its Base64 is well formed, and decodes;
 *   - the decoded image is neither empty/truncated nor over its byte bound;
 *   - it starts like the JPEG it claims to be;
 *   - its encoding is canonical, so one byte string has one identity;
 *   - the recomputed content hash equals the supplied fingerprint.
 *
 * The category is passed through untouched. It is INPUT: the existing
 * eligibility authority (vtoEligibility.ts) canonicalizes it and applies the
 * supported-category allowlist, exactly as for every other source.
 *
 * NOTHING HERE IS LOGGED. A refusal carries a short fixed reason code; the
 * payload, the hash and the category text never leave this function except as
 * the resolved garment handed back to the orchestrator.
 */

import {
  VTO_GARMENT_CONTENT_HASH_VERSION,
  VTO_GARMENT_PAYLOAD_MAX_CHARS,
  VTO_INLINE_GARMENT_MAX_BYTES,
  VTO_INLINE_GARMENT_MEDIA_TYPES,
  VTO_INLINE_GARMENT_MIN_BYTES,
  VTO_USER_SUPPLIED_GARMENT_SOURCE_TYPE,
} from './vtoContract.ts';

export type UserSuppliedVtoGarmentSource = {
  type: typeof VTO_USER_SUPPLIED_GARMENT_SOURCE_TYPE;
  contentHash: string;
  contentHashVersion: typeof VTO_GARMENT_CONTENT_HASH_VERSION;
};

export type UserSuppliedVtoGarment = {
  /** Stable CONTENT identity. Derived here, never taken from the caller. */
  productRef: string;
  /** Caller-supplied text; the eligibility authority canonicalizes it. */
  category: string;
  /** The validated inline garment. Request-scoped; never stored or logged. */
  garmentDataUri: string;
  /** Stable identity for the reservation key. Never the bytes. */
  mediaIdentity: string;
  source: UserSuppliedVtoGarmentSource;
};

export type UserSuppliedVtoGarmentResolution =
  | { ok: true; garment: UserSuppliedVtoGarment }
  /** `detail` is a fixed reason code for server logs. Never caller content. */
  | { ok: false; code: 'invalid_garment_input'; detail: string };

const CONTENT_HASH_PATTERN = /^[0-9a-f]{64}$/;
const INLINE_GARMENT_PREFIXES: readonly string[] = VTO_INLINE_GARMENT_MEDIA_TYPES.map(
  (mediaType) => `data:${mediaType};base64,`,
);
const BASE64_BODY_PATTERN = /^[A-Za-z0-9+/]+={0,2}$/;

function refuse(detail: string): UserSuppliedVtoGarmentResolution {
  return { ok: false, code: 'invalid_garment_input', detail };
}

/** True when `value` NAMES this source, whatever else is wrong with it. The
 *  orchestrator uses this to pick the branch; validity is decided by
 *  {@link resolveUserSuppliedVtoGarment}. */
export function isUserSuppliedVtoGarmentSource(value: unknown): boolean {
  return !!value && typeof value === 'object' && !Array.isArray(value)
    && (value as { type?: unknown }).type === VTO_USER_SUPPLIED_GARMENT_SOURCE_TYPE;
}

function decodeBase64(base64: string): Uint8Array | null {
  try {
    const binary = atob(base64);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
    return bytes;
  } catch {
    return null;
  }
}

function encodeBase64(bytes: Uint8Array): string {
  // Chunked on a multiple of 3 so every chunk encodes without padding and the
  // pieces concatenate into exactly the canonical encoding of the whole.
  const chunkSize = 0x8000 - (0x8000 % 3);
  let out = '';
  for (let i = 0; i < bytes.length; i += chunkSize) {
    out += btoa(String.fromCharCode(...bytes.subarray(i, i + chunkSize)));
  }
  return out;
}

async function sha256Hex(value: string): Promise<string> {
  const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(value));
  return Array.from(new Uint8Array(digest), (b) => b.toString(16).padStart(2, '0')).join('');
}

/**
 * Validates an inline garment against its supplied fingerprint.
 *
 * Consumes ONLY `source`, `dataUri` and `category` from the caller's garment
 * object. A caller URL, product reference, device-local id, user id, provider
 * or price is never read, so none of them can influence what is generated.
 */
export async function resolveUserSuppliedVtoGarment(
  garment: Record<string, unknown>,
): Promise<UserSuppliedVtoGarmentResolution> {
  const source = garment.source as Record<string, unknown> | null | undefined;
  if (!isUserSuppliedVtoGarmentSource(source)) return refuse('garment_source_shape');
  if (source!.contentHashVersion !== VTO_GARMENT_CONTENT_HASH_VERSION) {
    return refuse('garment_hash_version');
  }
  const contentHash = source!.contentHash;
  if (typeof contentHash !== 'string' || !CONTENT_HASH_PATTERN.test(contentHash)) {
    return refuse('garment_hash_shape');
  }

  const dataUri = garment.dataUri;
  if (typeof dataUri !== 'string' || !dataUri) return refuse('garment_media_missing');
  // The explicit encoded bound, checked before any decode work.
  if (dataUri.length > VTO_GARMENT_PAYLOAD_MAX_CHARS) return refuse('garment_media_too_large');

  const prefix = INLINE_GARMENT_PREFIXES.find((candidate) => dataUri.startsWith(candidate));
  if (!prefix) return refuse('garment_media_type');
  const base64 = dataUri.slice(prefix.length);
  if (!base64 || base64.length % 4 !== 0 || !BASE64_BODY_PATTERN.test(base64)) {
    return refuse('garment_media_encoding');
  }

  const bytes = decodeBase64(base64);
  if (!bytes) return refuse('garment_media_undecodable');
  if (bytes.length < VTO_INLINE_GARMENT_MIN_BYTES) return refuse('garment_media_too_small');
  if (bytes.length > VTO_INLINE_GARMENT_MAX_BYTES) return refuse('garment_media_too_large');
  // JPEG start-of-image. A payload labelled image/jpeg that is not one is not
  // the normalized source, whatever its hash says.
  if (bytes[0] !== 0xff || bytes[1] !== 0xd8 || bytes[2] !== 0xff) {
    return refuse('garment_media_not_jpeg');
  }

  // One byte string, one identity: a non-canonical encoding of the same bytes
  // is refused rather than hashed, so the fingerprint cannot be satisfied by
  // two different request bodies.
  const canonical = encodeBase64(bytes);
  if (canonical !== base64) return refuse('garment_media_noncanonical');

  // The fingerprint is RECOMPUTED, never trusted.
  const recomputed = await sha256Hex(canonical);
  if (recomputed !== contentHash) return refuse('garment_hash_mismatch');

  return {
    ok: true,
    garment: {
      productRef: `${VTO_USER_SUPPLIED_GARMENT_SOURCE_TYPE}:${contentHash}`,
      category: typeof garment.category === 'string' ? garment.category : '',
      garmentDataUri: `${prefix}${canonical}`,
      mediaIdentity:
        `${VTO_USER_SUPPLIED_GARMENT_SOURCE_TYPE}/${VTO_GARMENT_CONTENT_HASH_VERSION}/${contentHash}`,
      source: {
        type: VTO_USER_SUPPLIED_GARMENT_SOURCE_TYPE,
        contentHash,
        contentHashVersion: VTO_GARMENT_CONTENT_HASH_VERSION,
      },
    },
  };
}
