// LiveVTOPerceptionProvider.swift
//
// STATUS: unbuilt scaffolding. Never compiled in this session — see
// native/README.md's "Emulator-native validation lane" section for exactly
// why (no macOS/Xcode host is possible in this cloud sandbox; that is a
// structural fact about the execution environment, not something a longer
// session could resolve).
//
// Written to satisfy the emulator-native validation lane's Section 4
// two-mode perception-provider requirement:
//
//   "If the intended production model cannot execute in the emulator:
//    Create a provider adapter with two modes: REAL LOCAL MODEL... NATIVE
//    REPLAY PERCEPTION. Do not fake 'model validated' when replay mode is
//    used."
//
// FrameSource and PerceptionProvider are the mechanism. RealLocalPoseProvider
// is a TODO stub (see docs/vto-native-device-handoff.md Section 2 — the
// pose-model decision has not been made and requires device measurement).
// NativeReplayPerceptionProvider parses the JSON shape defined in
// packages/evaluation/src/nativeReplayFixture.ts (`formatVersion: 1`,
// `frameSource: "NATIVE_REPLAY_FIXTURE"`) — that TypeScript file is the
// source of truth for the format; this file mirrors it, never the reverse,
// same convention as nativeView.ts's relationship to this module's command
// surface.

import Foundation

// MARK: - Frame source

/// Where camera frames for a session originate. Only EMULATOR_CAMERA and
/// SIMULATOR_CAMERA ever produce a live AVCaptureSession frame; a
/// NATIVE_REPLAY_FIXTURE session never opens a camera at all. Evidence
/// generated by this session labels every artifact with the exact case that
/// produced it — never claim EMULATOR_CAMERA or SIMULATOR_CAMERA evidence
/// from a NATIVE_REPLAY_FIXTURE run.
enum FrameSource: String {
  case emulatorCamera = "EMULATOR_CAMERA"
  case simulatorCamera = "SIMULATOR_CAMERA"
  case nativeReplayFixture = "NATIVE_REPLAY_FIXTURE"
}

// MARK: - BodyFrame (mirror of live-vto-contract's bodyFrame.ts)

/// Field-for-field mirror of `@kscan-live-vto/contract`'s `BodyFrame`. Keep
/// this struct's fields in the same order and with the same names as
/// bodyFrame.ts — a native renderer or an evaluation export diffing the two
/// depends on that correspondence being exact, not just "close enough".
struct Point2D: Codable {
  let u: Double
  let v: Double
}

/// Mirrors bodyFrame.ts's `Landmark` discriminated union. Swift has no
/// built-in tagged union with this exact shape, so this uses Codable's
/// keyed-container decoding to accept either `{present: true, point, confidence}`
/// or `{present: false}` — the same two shapes the TypeScript type allows,
/// deliberately not a third "point defaults to origin" case. See
/// bodyFrame.ts's header: "Never substitute a guessed (0,0) or a stale value
/// here."
enum Landmark: Codable {
  case present(point: Point2D, confidence: Double)
  case absent

  private enum CodingKeys: String, CodingKey {
    case present, point, confidence
  }

  init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    let isPresent = try container.decode(Bool.self, forKey: .present)
    if isPresent {
      let point = try container.decode(Point2D.self, forKey: .point)
      let confidence = try container.decode(Double.self, forKey: .confidence)
      self = .present(point: point, confidence: confidence)
    } else {
      self = .absent
    }
  }

  func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    switch self {
    case .present(let point, let confidence):
      try container.encode(true, forKey: .present)
      try container.encode(point, forKey: .point)
      try container.encode(confidence, forKey: .confidence)
    case .absent:
      try container.encode(false, forKey: .present)
    }
  }
}

struct BodyFrame: Codable {
  let timestamp: Double

  let headCenter: Landmark
  let noseOrHeadDirection: Landmark
  let neckCenter: Landmark

  let leftShoulder: Landmark
  let rightShoulder: Landmark
  let leftElbow: Landmark
  let rightElbow: Landmark
  let leftWrist: Landmark
  let rightWrist: Landmark

  let chestCenter: Landmark
  let waistCenter: Landmark
  let leftHip: Landmark
  let rightHip: Landmark

  let torsoCenter: Landmark
  let torsoWidth: Double?
  let torsoHeight: Double?
  let torsoRotation: Double?

  let trackingConfidence: Double
}

// MARK: - Perception provider

/// The two-mode adapter Section 4 requires. Neither conforming type below
/// has run in this session — REAL LOCAL MODEL because no device/simulator
/// with a pose runtime is reachable, NATIVE REPLAY PERCEPTION because there
/// is no Swift compiler in this sandbox to build even the replay path
/// against. Both remain TODO/unverified; see native/README.md.
protocol PerceptionProvider {
  var frameSource: FrameSource { get }
  /// Begin producing BodyFrame values via `onFrame`. Never emits a raw
  /// camera frame, mask, or provider-specific landmark ID — only the
  /// vendor-neutral BodyFrame shape above, matching Section 21's "no
  /// downstream package may import provider-specific types" rule extended
  /// to this boundary too.
  func start(onFrame: @escaping (BodyFrame) -> Void, onError: @escaping (Error) -> Void)
  func stop()
}

/// TODO(P1-B2): wraps Vision's VNDetectHumanBodyPoseRequest (see
/// docs/vto-native-device-handoff.md Section 2, candidate B) or a MediaPipe
/// Pose Landmarker Task build, once device measurement picks one. Requires
/// EMULATOR_CAMERA or SIMULATOR_CAMERA — this type must refuse to run
/// against NATIVE_REPLAY_FIXTURE.
final class RealLocalPoseProvider: PerceptionProvider {
  let frameSource: FrameSource

  init(frameSource: FrameSource) {
    precondition(frameSource != .nativeReplayFixture, "RealLocalPoseProvider requires a live camera frame source")
    self.frameSource = frameSource
  }

  func start(onFrame: @escaping (BodyFrame) -> Void, onError: @escaping (Error) -> Void) {
    // TODO: not implemented. No pose runtime has been integrated or run in
    // this session. Calling this today is a programmer error, not a
    // silent no-op — production code must not construct this type until
    // Section 2's decision is made and the runtime is actually wired in.
    fatalError("RealLocalPoseProvider.start is not implemented — see docs/vto-native-device-handoff.md Section 2")
  }

  func stop() {}
}

enum NativeReplayFixtureError: Error {
  case malformedJSON(String)
  case wrongFrameSource(String)
}

/// Consumes the JSON fixture format from
/// packages/evaluation/src/nativeReplayFixture.ts entirely on the native
/// side, per Section 3: "Do not route fixture frames through JS merely
/// because the environment lacks a physical camera." This type never talks
/// to the Expo/React Native bridge — it is constructed and driven from
/// native code, with the fixture bundled as an app resource.
///
/// Structural parsing only. Validation equivalent to
/// `validateNativeReplayFixture` (frameCount match, monotonic timestamps,
/// minimal-pose sanity) has NOT been ported here — this type has never run
/// against a real JSONDecoder, and porting untested validation logic would
/// be worse than porting none, per Section 41's spirit ("port once a device
/// proves the approach is right"). A native implementer should port that
/// function's checks alongside this type's first real test run, not before.
final class NativeReplayPerceptionProvider: PerceptionProvider {
  let frameSource: FrameSource = .nativeReplayFixture
  private let fixtureData: Data
  private var isRunning = false

  init(fixtureData: Data) {
    self.fixtureData = fixtureData
  }

  func start(onFrame: @escaping (BodyFrame) -> Void, onError: @escaping (Error) -> Void) {
    isRunning = true
    do {
      let decoder = JSONDecoder()
      struct Manifest: Codable { let frameSource: String }
      struct Fixture: Codable { let manifest: Manifest; let frames: [BodyFrame] }
      let fixture = try decoder.decode(Fixture.self, from: fixtureData)
      guard fixture.manifest.frameSource == FrameSource.nativeReplayFixture.rawValue else {
        onError(NativeReplayFixtureError.wrongFrameSource(fixture.manifest.frameSource))
        return
      }
      // TODO: real replay would pace these against each frame's timestamp
      // (or the session's declared nominal frame rate) rather than emitting
      // synchronously; timing-accurate replay has not been implemented or
      // measured here.
      for frame in fixture.frames where isRunning {
        onFrame(frame)
      }
    } catch {
      onError(NativeReplayFixtureError.malformedJSON("\(error)"))
    }
  }

  func stop() {
    isRunning = false
  }
}
