#!/usr/bin/env node
'use strict';

/**
 * Regression tests for DEF-B29-SVV-013A.
 *
 * The candidate artifact scanner treated the literal
 * `-----BEGIN PRIVATE KEY-----` marker as a BLOCKER on its own. Three Build 29
 * Apple auth constructs therefore blocked staging certification while carrying
 * no key material at all:
 *
 *   - a helper that BUILDS a PEM from generated bytes
 *   - a tiny fake test fixture
 *   - a regex that PARSES PEM input
 *
 * A marker is not a credential. Detection is now semantic: a complete
 * BEGIN/END pair with matching labels, a base64 body that survives a decode
 * round trip, a non-trivial decoded payload, and a leading DER SEQUENCE tag.
 *
 * These tests generate REAL private keys at run time with node:crypto rather
 * than committing key material, and they assert both directions: real keys
 * still block, and the Apple constructs pass WITHOUT any allowlist.
 */

const test = require('node:test');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..', '..');
const { scanFile, RULES } = require('../../security/scripts/scan-candidate-artifacts.js');

/** The marker-only rule the scanner used before this fix. */
const LEGACY_MARKER_RULE = /-----BEGIN(?: [A-Z]+)? PRIVATE KEY-----/;

function tmpFile(name, contents) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'kscan-pk-'));
  const file = path.join(dir, name);
  fs.writeFileSync(file, contents, 'utf8');
  return file;
}

const privateKeyFindings = (file) => scanFile(file).filter((f) => f.rule === 'PRIVATE_KEY');

// ── real key material must still block ───────────────────────────────────────

const REAL_KEYS = [
  ['PKCS#8 Ed25519', () => crypto.generateKeyPairSync('ed25519', {
    privateKeyEncoding: { type: 'pkcs8', format: 'pem' }, publicKeyEncoding: { type: 'spki', format: 'pem' },
  }).privateKey],
  ['PKCS#8 EC P-256', () => crypto.generateKeyPairSync('ec', {
    namedCurve: 'prime256v1',
    privateKeyEncoding: { type: 'pkcs8', format: 'pem' }, publicKeyEncoding: { type: 'spki', format: 'pem' },
  }).privateKey],
  ['SEC1 EC P-256', () => crypto.generateKeyPairSync('ec', {
    namedCurve: 'prime256v1',
    privateKeyEncoding: { type: 'sec1', format: 'pem' }, publicKeyEncoding: { type: 'spki', format: 'pem' },
  }).privateKey],
  ['PKCS#1 RSA 2048', () => crypto.generateKeyPairSync('rsa', {
    modulusLength: 2048,
    privateKeyEncoding: { type: 'pkcs1', format: 'pem' }, publicKeyEncoding: { type: 'spki', format: 'pem' },
  }).privateKey],
  ['encrypted PKCS#8', () => crypto.generateKeyPairSync('ec', {
    namedCurve: 'prime256v1',
    privateKeyEncoding: { type: 'pkcs8', format: 'pem', cipher: 'aes-256-cbc', passphrase: 'test-passphrase' },
    publicKeyEncoding: { type: 'spki', format: 'pem' },
  }).privateKey],
];

for (const [label, make] of REAL_KEYS) {
  test(`SVV-013A: a real ${label} with literal newlines is BLOCKED`, () => {
    const file = tmpFile('leaked.pem', make());
    const findings = privateKeyFindings(file);
    assert.equal(findings.length, 1, `${label} must be detected`);
    assert.equal(findings[0].severity, 'BLOCKER');
  });
}

test('SVV-013A: a real key embedded with ESCAPED newlines is BLOCKED', () => {
  // How a key actually leaks into source or JSON: one line, \n escaped.
  const pem = crypto.generateKeyPairSync('ed25519', {
    privateKeyEncoding: { type: 'pkcs8', format: 'pem' }, publicKeyEncoding: { type: 'spki', format: 'pem' },
  }).privateKey.trim();
  const escaped = pem.split('\n').join('\\n');
  const file = tmpFile('config.ts', `export const APPLE_PRIVATE_KEY = '${escaped}';\n`);

  const findings = privateKeyFindings(file);
  assert.equal(findings.length, 1, 'an escaped-newline key must still be detected');
  assert.equal(findings[0].severity, 'BLOCKER');
});

test('SVV-013A: a real key inside a JSON string is BLOCKED', () => {
  const pem = crypto.generateKeyPairSync('ed25519', {
    privateKeyEncoding: { type: 'pkcs8', format: 'pem' }, publicKeyEncoding: { type: 'spki', format: 'pem' },
  }).privateKey.trim();
  const file = tmpFile('secrets.json', JSON.stringify({ applePrivateKey: pem }, null, 2));
  assert.equal(privateKeyFindings(file).length, 1);
});

// ── source constructs that are not credentials must pass ─────────────────────

const NON_CREDENTIALS = [
  ['a PEM parser regex', 'const match = /-----BEGIN PRIVATE KEY-----([\\s\\S]+?)-----END PRIVATE KEY-----/.exec(input);\n'],
  ['a PEM builder helper', 'const pem = `-----BEGIN PRIVATE KEY-----\\n${body}\\n-----END PRIVATE KEY-----`;\n'],
  ['a tiny fake fixture', "const APPLE_PRIVATE_KEY = '-----BEGIN PRIVATE KEY-----AAAA-----END PRIVATE KEY-----';\n"],
  ['a marker with no END', 'const banner = "-----BEGIN PRIVATE KEY-----";\n'],
  ['mismatched BEGIN/END labels', '-----BEGIN RSA PRIVATE KEY-----\nAAAA\n-----END EC PRIVATE KEY-----\n'],
];

for (const [label, contents] of NON_CREDENTIALS) {
  test(`SVV-013A: ${label} does NOT block`, () => {
    const file = tmpFile('source.ts', contents);
    assert.deepEqual(privateKeyFindings(file), [], `${label} carries no key material`);
    // The construct really does contain the marker the old rule fired on.
    assert.match(contents, LEGACY_MARKER_RULE, 'the legacy marker rule would have blocked this');
  });
}

test('SVV-013A: a long structureless base64 blob is not reported as a key', () => {
  // Rejected by the DER check: no leading SEQUENCE tag.
  const blob = Buffer.alloc(512, 0x41).toString('base64');
  const file = tmpFile('blob.pem', `-----BEGIN PRIVATE KEY-----\n${blob}\n-----END PRIVATE KEY-----\n`);
  assert.deepEqual(privateKeyFindings(file), []);
});

// ── the real Build 29 files, unmodified and unallowlisted ────────────────────

const APPLE_FILES = [
  'supabase/functions/_shared/appleAuth/appleAuth.test.ts',
  'supabase/functions/_shared/appleAuth/appleClientSecret.ts',
];

for (const rel of APPLE_FILES) {
  test(`SVV-013A: ${path.basename(rel)} passes without an allowlist`, () => {
    const file = path.join(ROOT, rel);
    assert.ok(fs.existsSync(file), `${rel} must exist in the candidate`);
    assert.deepEqual(privateKeyFindings(file), [], 'no real key material is present');

    // Prove the file is still scanned and still contains the marker: this is a
    // semantic improvement, not an exclusion.
    const text = fs.readFileSync(file, 'utf8');
    assert.match(text, LEGACY_MARKER_RULE, 'the old marker rule blocked this file');
  });
}

test('SVV-013A: test files are still scanned, not excluded', () => {
  const file = path.join(ROOT, 'supabase/functions/_shared/appleAuth/appleAuth.test.ts');
  const pem = crypto.generateKeyPairSync('ed25519', {
    privateKeyEncoding: { type: 'pkcs8', format: 'pem' }, publicKeyEncoding: { type: 'spki', format: 'pem' },
  }).privateKey;
  // A real key planted in a *.test.ts must still be caught.
  const planted = tmpFile('appleAuth.test.ts', pem);
  assert.equal(privateKeyFindings(planted).length, 1, 'a .test.ts file is not exempt');
  assert.ok(fs.existsSync(file));
});

// ── the other rules are untouched ────────────────────────────────────────────

test('SVV-013A: the remaining secret rules are unchanged and still fire', () => {
  const names = RULES.map(([name]) => name);
  assert.ok(!names.includes('PRIVATE_KEY'), 'PRIVATE_KEY is no longer a line rule');
  for (const expected of ['SUPABASE_SERVICE_KEY', 'SUPABASE_ACCESS_TOKEN', 'OPENAI_API_KEY',
    'GITHUB_TOKEN', 'AWS_ACCESS_KEY', 'DATABASE_URL_WITH_PASSWORD']) {
    assert.ok(names.includes(expected), `${expected} must remain`);
  }

  const samples = [
    ['SUPABASE_SERVICE_KEY', `sb_secret_${'a'.repeat(24)}`],
    ['SUPABASE_ACCESS_TOKEN', `sbp_${'a'.repeat(40)}`],
    ['OPENAI_API_KEY', `sk-${'A'.repeat(32)}`],
    ['GITHUB_TOKEN', `ghp_${'A'.repeat(36)}`],
    ['AWS_ACCESS_KEY', `AKIA${'B'.repeat(16)}`],
    ['DATABASE_URL_WITH_PASSWORD', 'postgresql://user:hunter2pw@db.example.com:5432/app'],
  ];
  for (const [rule, sample] of samples) {
    const file = tmpFile('cfg.env', `VALUE=${sample}\n`);
    const hits = scanFile(file).filter((f) => f.rule === rule);
    assert.equal(hits.length, 1, `${rule} must still fire`);
  }
});

test('SVV-013A: findings carry a fingerprint and never the key material', () => {
  const pem = crypto.generateKeyPairSync('ed25519', {
    privateKeyEncoding: { type: 'pkcs8', format: 'pem' }, publicKeyEncoding: { type: 'spki', format: 'pem' },
  }).privateKey;
  const file = tmpFile('leaked.pem', pem);
  const [finding] = privateKeyFindings(file);

  assert.match(finding.fingerprint, /^[a-f0-9]{16}$/);
  const serialized = JSON.stringify(finding);
  const body = pem.replace(/-----[A-Z ]+-----/g, '').replace(/\s+/g, '');
  assert.ok(!serialized.includes(body), 'the key body must never reach the artifact');
  assert.ok(!serialized.includes(body.slice(0, 32)), 'not even a prefix of it');
  assert.ok(!serialized.includes('BEGIN'), 'no PEM content in the finding');
});
